server:
  port: 4000
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: ${DATASOURCE_PASSWORD}
    url: jdbc:postgresql://localhost:5432/mrsburguer
    username: ${DATASOURCE_USER}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
